### ISSUE TITLE
strange SSL behavior within the AppImage

### ISSUE THREAD

**Issue by knro** [probonopd/linuxdeployqt#110]
I'm trying to make an AppImage for my Chart Downloader App here: https://github.com/knro/chartdownloader

I already used windowsdeployqt and macdeployqt and boy was I glad to find linuxdeployqt, thanks for the spectacular effort!!

However, I initially built the app image against Qt 5.8 that I downloaded from Qt website, but upon executing the AppImage on a test machine, all SSL GET requests fail almost immediately and I see the following in the console:

qt.network.ssl: QSslSocket: cannot resolve SSLv2_client_method
qt.network.ssl: QSslSocket: cannot resolve SSLv2_server_method

I tried using bundle non-qt libs as well with the same result. So then I checked Qt 5.9 from GIT and built it on my machine and then recompiled against 5.9 and the above SSL errors disappeared from the AppImage, however, now instead of downloading the designated URL, it downloads another relative URL, perhaps due to some redirect. So I added the following:

#if (QT_VERSION >= QT_VERSION_CHECK(5, 9, 0))
manager.setRedirectPolicy(QNetworkRequest::SameOriginRedirectPolicy);
#endif

But it still fails and downloads another relative URL. The URL I am trying to GET is this:

https://www.faa.gov/air_traffic/flight_info/aeronav/digital_products/dtpp/search/results/?cycle=1705&ident=KSAN

On my machine, I get the result of the GET without any issues, but when using an AppImage, I get this URL:

https://www.faa.gov/air_traffic/flight_info/aeronav/digital_products/dtpp/search

I'm not sure why AppImage is behaving in this way. I tried to use Cookie Jar to store cookies to see if they have any issues since when I was running wget on the same URL, I saw a cookie getting set. Btw, wget works just fine on the test machine. I made the following very simple sample_https app that demonstrated this behavior:

https://www.dropbox.com/s/yeris9y2g31qazc/sample_https.tar.gz?dl=0

If you compile locally, you'll get the URL result just fine (result.html about 43kb), but in the AppImage, you get the search URL (about 33kb). 

This is also a link to the AppImage created for the above sample application: https://www.dropbox.com/s/49wldg9wl9bc1yo/Application-x86_64.AppImage?dl=0

Any help appreciated!

**Comment by probonopd** [comment]
Thanks @knro for your feedback. I have never used Qt 5.9 so far so I cannot comment on that. Which build system did you test this on?

For the best reproducible results I recommend to use Ubuntu Trusty and https://launchpad.net/~beineri/+archive/ubuntu/opt-qt58-trusty (because that's what I am using `linuxdeployqt` with on [Travis CI](http://travis-ci.org)). Can you reproduce the issue with that? That would be a good starting point for further debugging/bugfixing.

**Comment by knro** [comment]
I am building this on KDE Neon (16.04) and tested it in Mint 18.1 (VM) and Ubuntu Gnome 17.04 (VM), I also tested it on another KDE Neon Machine, and all the AppImages failed with the same reason. I tried to build against Qt 5.8 initially, but as I said, it failed with the SSL error above. I will download 14.04 and test on it.

**Comment by probonopd** [comment]
If you can do it on [Travis CI](http://travis-ci.org/) then it will be easier for me to debug and to work collaboratively on it.

**Comment by knro** [comment]
Done. it's here: https://github.com/knro/appImageSSLTest

Though I'm not exactly sure where it uploaded the AppImage to?

**Comment by probonopd** [comment]
What happens if you unpack the AppImage and manually delete the SSL libs, then run AppRun?

**Comment by probonopd** [comment]
You can see the download URL at the end of the Travis CI build log if all went well.

**Comment by knro** [comment]
Well, in Travis all went well but I can't see the URL. Also, as I said, in 14.04, the application itself fails to download. The same application works fine in 16.04. This is without AppImage.

With AppImage, I'd imagine it would also fail on 14.04, and on 16.04+, I tested it and it fails. If I delete the bundled libssl, then libQt5Network just points to the system SSL. For Qt5 provided by Qt itself, it is compiled as to load libssl in run time, so it is not explicitly linked to it. I made custom builds when it links directly to it, but that made no difference.

**Comment by probonopd** [comment]
@knro I see, you are trying to upload to GitHub Releases. For that to work, you need to get a token from GitHub and put it into the Travis CI settings of your project. The Travis CI build logfile says:

```
$ bash ./upload.sh appImageSSLTest-continuous-x86_64.AppImage
TRAVIS_COMMIT: 1e3423f4787078c445a45184e9d8d37c31c914a3
$GITHUB_TOKEN missing, please set it in the Travis CI settings of this project
You can get one from https://github.com/settings/tokens
```

**Comment by knro** [comment]
I did that, but it's still not uploading, what's the issue?

https://api.travis-ci.org/jobs/234337666/log.txt?deansi=true

**Comment by hipersayanX** [comment]
I had the same problem but it's no related to AppImage and neither linuxdeployqt. This is because of some binary incompatibilities between [openssl-1.0.2l and openssl-1.1.0f](https://www.openssl.org/source/), Qt only supports the first. More info [here](https://wiki.openssl.org/index.php/OpenSSL_1.1.0_Changes#Qt).

**Comment by knro** [comment]
How come the application works fine then on my Ubuntu machine? I also created installers for both Windows and Mac (using windowsdeployqt and macdeployqt) and they both work OK on the target platforms.

**Comment by hipersayanX** [comment]
@knro, your build system is Trusty, right? What is the target system? Does the target system have libssl.so.1.0 installed?

In my case, i did compiled my app in Trusty, and when running it in Debian Sid, it give the same errors as you and no connection, because openssl 1.0 was not installed. In the case of Windows, I upgraded mingw-w64-openssl to 1.1, but I had Qt still compiled for openssl 1.0, an give me the same errors. When trying to compile Qt with openssl 1.1, it give me an error at compile time.

So everything is pointing to an incompatibility between this two versions of openssl.

**Comment by probonopd** [comment]
Continues on https://github.com/probonopd/linuxdeployqt/issues/209. Please also see https://github.com/probonopd/linuxdeployqt/issues/110.
