### ISSUE TITLE
"appimage" parameter screws library removal logic

### ISSUE THREAD

**Issue by Ribtoks** [probonopd/linuxdeployqt#118]
If you cleanup odd dynamic libraries after the first "bundling" run of `linuxdeployqt` and you run it second time with `-appimage` parameter, it defaults the `-bundle-non-qt-libs`. This causes already removed libraries to be bundled again which renders it useless on the contrary to running `appimagetool` directly.

Proposed fix is **not** to default `bundle-non-qt-libs` when you set `appimage` parameter.

**Comment by probonopd** [comment]
`linuxeployqt` is supposed to be easy to use and not provide more options than needed. In 99.9% of cases `linuxeployqt` users should rely on the built-in blacklist rather than second-guess it. 

For edge cases like the one you describe, it's best to run `linuxdeployqt` twice without `-appimage`, and once you are satisfied with the AppDir run `appimagetool` on it manually. It will put the contents of the AppDir into an AppImage without making any changes to it.

**Comment by Ribtoks** [comment]
@probonopd running `linuxdeployqt` twice is already ridiculous, because it's an obvious flaw (read "bug") inside.
**Hard-coding blacklist is a bug** because, first of all, it is not covering major linux distributions problems (kerberos not commented, libwind, libroken not available in OpenSUSE with specified name) and, secondly, the whole idea of hardcoding blacklist based on debian-like system is an awful decision by it's own.

> once you are satisfied with the AppDir run appimagetool on it manually
That was my very point - no need in `linuxdeployqt`s _-appimg_ parameter since it's buggy, messes your files and is best avoidable.

**Comment by probonopd** [comment]
So what do you suggest? Let every user find out the optimal blacklist on their own? I still think we should at least ship sane defaults (and as you point out, they need improvement).

**Comment by Ribtoks** [comment]
@probonopd I suggest removing hardcoded blacklist from binary and putting in into the file like _.blacklist_ and/or pass it as a parameter. Also you can supply the default one with `linuxdeployqt` distribution. Or having a parameter `-default-blacklist`. Anything that is flexible enough.
