### ISSUE TITLE
exclude list should be configurable

### ISSUE THREAD

**Issue by Optiligence** [probonopd/linuxdeployqt#166]
It’s a bit impractical that you have to change the source code to modify the exclude list. 
A command line arg for that would be nice, or an option to suppress recollection of all libraries which would allow just modifying the `lib` folder as necessary without getting changes overwritten with the next run. 

In my case i wanted to exclude python because that doesn’t seem to be distributable in a manner that works cross-distro and since it relies on the existence of the rest of the python environment anyway. (comments about different experiences welcome)

**Comment by probonopd** [comment]
Hi @Optiligence and welcome to linuxdeployqt. The reason we don't make the list configurable is that we think that if changes should be made to it, it should be changed in a way so that everyone can benefit from the change. Also, ideally we'd like to discuss suggestions for change. 

As for Python, we recommend to bundle it (the interpreter and its libraries and standard library) inside the AppImage. There are several AppImage examples that do it, for example Cura, which is a Python Qt application.

If you really want to exclude a library, you could run prepare the AppDir using `linuxdeployqt -bundle-non-qt-libs`, and then run `appimagetool` on the AppDir.

**Comment by Optiligence** [comment]
While i appreciate the idea to find consensus what works and integrate that, i disagree that forcing something that is nice. 

If the goal is to have a self contained (for it’s purpose complete) python environment, sure, but we want our users to be able to integrate our program into their python environment and still use linuxdeployqt…

There is no Cura listed in the readme and i couldn’t find anything linuxdeployqt (or an appimage) in https://github.com/Ultimaker/Cura if that’s it. 

For the last part you’d have to download and run AppImage separately, why?

**Comment by probonopd** [comment]
> If the goal is to have a self contained (for it’s purpose complete) python environment, sure, but we want our users to be able to integrate our program into their python environment and still use linuxdeployqt…

That's really a special case. Generally we recommend to bundle everything inside the AppImage that cannot reasonably be expected to be part of each target system (distribution) in a recent enough version.

In your case, please prepare the AppDir using `linuxdeployqt -bundle-non-qt-libs`, and then run `appimagetool` on the AppDir. You can get `appimagetool` (which `linuxdeployqt` internally uses) by running `linuxdeployqt*.AppImage --appimage-extract`...
