### ISSUE TITLE
Why is libjack.so.0 blacklisted?

### ISSUE THREAD

**Issue by tblrchstr** [probonopd/linuxdeployqt#336]
I've noticed that `libjack.so.0` has been blacklisted (recently). Unfortunately the app I'm trying to package depends on it. What's wrong with that library? Should I ask the user to install it manually before running the AppImage, given the current status?

**Comment by probonopd** [comment]
`libjack.so.0` is blacklisted because it belongs to the JACK installation on the target system. It must exactly match the rest of the installed JACK system. Hence we are using this library from the target system. If the target system does not have this library installed, then the target system does not have JACK installed and it would not work, anyway.

It's probably best not to use JACK, or bundle two versions (one with, one without JACK) inside the AppImage and write a wrapper script that decides which one to run, based on whether JACK is installed on the target system.
