### ISSUE TITLE
ERROR: The host system is too new.

### ISSUE THREAD

**Issue by jradxl** [probonopd/linuxdeployqt#377]
Trying to build an AppImage on Bionic 18.04
This is annoying. My app does not work on 16.04, and I don't want to support on 16.04
Choice of oldest system should be choice made by User and not the provider of the tool.

If I find where this limitation is controlled in linuxdeployqt's source and remove it, will linuxdeployqt still work?

$ linuxdeployqt-continuous-x86_64.AppImage --help
linuxdeployqt de6d873 (commit 6e359c5), build 689 built on 2019-05-10 17:10:54 UTC
ERROR: The host system is too new.
Please run on a system with a glibc version no newer than what comes with the oldest
currently still-supported mainstream distribution (xenial), which is glibc 2.23.
This is so that the resulting bundle will work on most still-supported Linux distributions.
For more information, please see
https://github.com/probonopd/linuxdeployqt/issues/340

**Comment by probonopd** [comment]
Please use the oldest still-supported LTS release of Ubuntu, which at this time is xenial.

**Comment by palxex** [comment]
I know the design is for the package able to run on as many distribution as possible. But we still have situations like debugging. Could there be an option to make it at least able to work on every distribution? Not needed to be default.

**Comment by maximilize** [comment]
There could be for example a `--force` option with warnings displayed. It really would be helpful for debugging reasons in some edge cases.

**Comment by sykhro** [comment]
Qt 5.15.0 requires OpenSSL 1.1 and Xenial's OpenSSL is too old, this can be a potential problem for some because the most popular Qt PPA ships without SSL support now (I happen to need 5.15.0 for some bugfixes, fortunately I don't need the SSL bits)

**Comment by probonopd** [comment]
Seems like this is yet another occurence of https://github.com/openssl/openssl/issues/5042 then. OpenSSL 1.1 should really have been called 2.0...

Pragmaticall speaking, I can see these options:

* Use another tool instead of `linuxdeployqt` such as https://github.com/AppImageCrafters/appimage-builder that can bundle _everything_, including OpenSSL, or
* Change the source code so that Qt < 5.15 becomes sufficient and hence OpenSSL 1.0 becomes sufficient
* Wait until the oldest still-supported Ubuntu LTS distribution will be shipping OpenSSL 1.1

**Comment by lzunsec** [comment]
I'm trying to generate an appimage for a binary that I do not have the sources, that is built for ubuntu 18.04. However, I can only use linuxdeployqt on ubuntu 16, so I get an error about glibc version:

` /lib/x86_64-linux-gnu/libc.so.6: version GLIBC_2.25' not found (required by /app/usr/myApp)"``

How should I overcome this? I see no solution

**Comment by probonopd** [comment]
Works as designed: `linuxdeployqt` simply cannot turn a binary that is built for ubuntu 18.04 into an AppImage that can run on all still-supported releases od Ubuntu.
Please ask the author of the application for a version that runs on all still-supported releases of Ubuntu including 16.04, or wait until 16.04 is no longer supported, or use another tool such as https://github.com/AppImageCrafters/appimage-builder or https://github.com/probonopd/go-appimage/ `appimagetool -s deploy`.

**Comment by martinrotter** [comment]
What am I missing? So there is no way to workaround the "warning"? For example for DEBUGGING purposes?

Do not take my words as ranting (I do know these kinds of situations as I develop FOSS project used by thousands of users too), but this is just ridiculous.

> linuxdeployqt does not have this functionality.

Are you saying linuxdeployqt technically cannot do that? Because I highly doubt so. What the hell?

**Comment by martinrotter** [comment]
> 

I see. Can those tools automagically aid Qt apps deployment like linuxdeloyqt does? Copying plugins etc.?
