### ISSUE TITLE
Running alternative binaries

### ISSUE THREAD

**Issue by rezodlub** [probonopd/linuxdeployqt#398]
I'd really like to have an option to run alternative binaries from within an AppImage. Maybe something like $ARGV0 approach, mentioned in https://discourse.appimage.org/t/call-alternative-binary-from-appimage/93/9

**Comment by probonopd** [comment]
It is already possibly by writing your own custom `AppRun` bash script, e.g., along the lines of https://github.com/wireshark/wireshark/blob/4d6509854cbde812470fe76c90dafca1ad7666e6/packaging/appimage/AppRun.

**Comment by rezodlub** [comment]
I know I can fix it on my side, but would have to apply the change and rebuild on every new release. That's why I wondered if you could add it to official release, so the functionality would always be present for all.

**Comment by probonopd** [comment]
You don't need to rebuild `linuxdeployqt`. Just copy your custom `AppRun` script into the AppDir before you run `linuxdeployqt` on it. Then `linuxdeployqt` will not overwrite the `AppRun` file, but leave it in place.

Since the majority of use cases for `linuxdeployqt` consist of one GUI application per AppImage, I am hesitant to add this functionality to `linuxdeployqt` itself.
