### ISSUE TITLE
How to run this tool on Fedora 30?

### ISSUE THREAD

**Issue by silvioprog** [probonopd/linuxdeployqt#412]
I have been trying to run `linuxdeployqt-6-x86_64.AppImage` on Fedora 30, but it fails with the following message:

```bash
./linuxdeployqt-6-x86_64.AppImage --help
linuxdeployqt 5 (commit 37631e5), build 631 built on 2019-01-25 22:47:58 UTC
ERROR: The host system is too new.
Please run on a system with a glibc version no newer than what comes with the oldest
still-supported mainstream distribution, which currently is glibc 2.20.
This is so that the resulting bundle will work on most still-supported Linux distributions.
For more information, please see
https://github.com/probonopd/linuxdeployqt/issues/340
```

It is strange, because the file is called `linuxdeployqt-*6*`, however, the first error line says `linuxdeployqt *5*`.

So, is there any trick to run `linuxdeployqt` on Fedora? I would appreciate not to depend on old Debian/Ubuntu-based distros to run it.

TIA for any help!

**Comment by probonopd** [comment]
* Please always use the latest continuous build. That one is already over a year old and does not contain the bugfixes made since then
* The tool has only been tested on Ubuntu trusty and Ubuntu xenial
* The tool may run on Fedora, although we didn't really test it there
* The latest version of Fedora on which I currently would expect this to work is Fedora 24. Later versions of Fedora are currently too new. It is clear that this tool will not work on Fedora 30 because Fedora 30 comes with a much newer glibc than what we can expect to be present on target systems (= still-supported LTS releases of Ubuntu etc.)
