### ISSUE TITLE
Doesn't work in newer ubuntu

### ISSUE THREAD

**Issue by MahdiHamidpour** [probonopd/linuxdeployqt#424]
Hi dear developer
This is a great tool but doesn't work in newer versions of ubuntu. How can we make "appimage" in ubuntu 19.10?

**Comment by magnus-gross** [comment]
Use `-unsupported-bundle-everything` to bypass the glibc version check

**Comment by probonopd** [comment]
Dear @MahdiHamidpour please build your application on the oldest still-supported LTS release, which is xenial at this time. Otherwise your AppImage will not work on all still-supported versions of Ubuntu. Thanks.

**Comment by probonopd** [comment]
> Use -unsupported-bundle-everything to bypass the glibc version check

It's undocumented and unsupported for a reason. It may produce broken results.

**Comment by MahdiHamidpour** [comment]
> Dear @MahdiHamidpour please build your application on the oldest still-supported LTS release, which is xenial at this time. Otherwise your AppImage will not work on all still-supported versions of Ubuntu. Thanks.

Thanks and regards. But I believe it's maybe a weakness in the project's software engineering. Why we should NOT use newer versions???

**Comment by probonopd** [comment]
Applications compiled against newer versions of the Linux userland libraries will not run on older ones. But applications compiled against older versions of the Linux userland libraries **will**  run on newer ones.

This is not specific to linuxdeployqt or AppImage. (It is the same e.g., on Windows - if you compile on Windows 10 then you cannot expect it to run on Windows 7).

**Comment by magnus-gross** [comment]
It's okay to use `-unsupported-bundle-everything` on your newer Ubuntu if you just want to try `linuxdeployqt` out. Of course, once you want to release an Appimage to the public, you should build that on the oldest available Ubuntu. There is no reason though to make such a secret about that option, the name already literally tells you that it is unsupported and there even is still a warning printed out during execution.
The way that the defaults of this tool go in the way of the developer isn't going to make the developer follow the recommended *final* packaging process, it's just going to turn away the dev and they are just bad defaults.

**Comment by probonopd** [comment]
It's better to develop on the oldest LTS. Developers who develop against the latest and greatest of everything are gonna having a hard time in the end. I've seen it time and again - once an app is developed on the latest and greatest systems, no one will care later to backport it so that it runs on all still-supported systems. Better do it the right way right from the beginning.

**Comment by MahdiHamidpour** [comment]
ok
please tell me how to develop and release an app on "Ubuntu 16.04 LTS" while using [Kvantum](https://github.com/tsujan/Kvantum)? 
Kvantum uses some packages that just supported in ubuntu 18 or newer. 

this is just an example.

**Comment by probonopd** [comment]
> Kvantum uses some packages that just supported in ubuntu 18 or newer.

You will need to build those packages on Ubuntu 16.04 LTS then.

**Comment by NotCompsky** [comment]
One use case is someone preserving software that they currently use, in order to safeguard against that software no longer being available/maintained after some years.

I agree with developing for the oldest supported Ubuntu - in fact I go one further and aim for removing the glibc dependencies entirely by making static binaries with musl - but it's infeasible to do that for all software you want to preserve (some of whose dependencies may not even have source code available).
