### ISSUE TITLE
Qt6 - ERROR: The host system is too new.

### ISSUE THREAD

**Issue by provirus** [probonopd/linuxdeployqt#466]
I am trying to use this application on Ubuntu 20.04 and I am getting that error:

> ERROR: The host system is too new.

I do understand that you want to support Ubuntu 16.04 (xenial), but per https://www.qt.io/product/qt6/technical-specifications , Qt6 supports `Ubuntu 20.04 (64bit Intel; gcc9)`.

In that case, it doesn't make sense to be more backward compatible than the library itself.

thanks

**Comment by probonopd** [comment]
> I am trying to use this application on Ubuntu 20.04

Your host system is too new. Please try on Ubuntu 16.04, which currently is the oldest still-supported one.
If Qt 6 only supports Ubuntu 20.04 and newer, then using it will become an option only once the oldest still-supported version of Ubuntu is 20.04, which will be in April 2023.

**Comment by probonopd** [comment]
An another option, you might try https://github.com/AppImageCrafters/appimage-builder or https://github.com/probonopd/go-appimage because they support building AppImages that are not only backward compatible but also forward compatible (which means you can build on Ubuntu 20.04 and run on 16.04).

**Comment by TheAssassin** [comment]
> An another option, you might try https://github.com/AppImageCrafters/appimage-builder or https://github.com/probonopd/go-appimage because they support building AppImages that are not only backward compatible but also forward compatible (which means you can build on Ubuntu 20.04 and run on 16.04).

Coming with significant downsides, too. But they're usually not mentioned.

**Comment by probonopd** [comment]
Yes, we should make a pro/con list (if one doesn't already exist) e.g., in the AppImage docs.

**Comment by TheAssassin** [comment]
There are a few, I think, but maybe not in the docs. I just would prefer if you'd mention at least the major downsides.
Often enough, I hear, "it's not an issue if the author keeps updating their AppImage constantly", but are authors ever told?

**Comment by provirus** [comment]
It doesn't make much sense that your application is specifically for Qt, but you do not want to support Qt 6 for a couple years...

> It always amazes me why anyone would develop anything that would not run on all still-supported systems.

Because that can be costly. Just think about how much money was wasted in supporting IE 6 for years.

**Comment by TheAssassin** [comment]
Very good point. I see it like this:

* First try to support all still-supported major desktop distros (usually, the baseline is the oldest still-supported Ubuntu LTS or maybe Debian (old)stable).
* If that isn't viable as of yet, choose the oldest you can and try to stick with it as long as possible, i.e., until this is the oldest still-supported LTS release.
* If you _have_ to move on, try to break the system for as few people as possible (realistically, for most apps, users have newer releases anyway).
* If you really can't do otherwise and are aware and have methods in place to mitigate the risks, "bundling everything" (i.e., creating something like a "static binary" equivalent AppImage) *can* be viable. But it should *always* be the last resort.

It makes just no sense to recommend this "bundle everything" as a *first* choice. But this is a big anti-pattern I've seen in the last year a lot. And I don't like this. Trading security for supporting likely zero users is a very bad trade-off.

This is why I see it more relaxed, and this reflects in my tools. linuxdeploy and its plugins just work. At most, they would write a warning if something is not following what I consider "best practices" (not rules).

**Comment by jheaff1** [comment]
Sure it’s best to *encourage* users of linuxdeployqt to support older Ubuntu versions, but **forcing** users is rather restrictive. Let developers make their own choice. I have a very close relationship with my customers and could instruct them to update to Ubuntu 20.04 as I’d like to use Qt6 and it wouldn’t be an issue. But I cannot move to Qt6 without finding an alternative to linuxdeployqt due to the enforcement of compatibility.

**Comment by probonopd** [comment]
Tools like https://github.com/AppImageCrafters/appimage-builder or https://github.com/probonopd/go-appimage `appimagetool -s deploy` might do what you like.
