### ISSUE TITLE
The latest linuxdeployqt version does not work on the Ubuntu 20.04.2 LTS

### ISSUE THREAD

**Issue by goodtang** [probonopd/linuxdeployqt#480]
If I run on the newer Ubuntu OS, it can not be OK , and the following error is written:

linuxdeployqt 6 (commit d41e234), build 724 built on 2020-07-31 15:51:47 UTC
ERROR: The host system is too new.
Please run on a system with a glibc version no newer than what comes with the oldest
currently still-supported mainstream distribution (xenial), which is glibc 2.23.
This is so that the resulting bundle will work on most still-supported Linux distributions.

And I check the issue https://github.com/probonopd/linuxdeployqt/issues/340 , but I am not sure this is the same result that I met now.  I can not find the way to make it work.

So , is this the final solution or any other way to work around?

**Comment by dachshund-ncu** [comment]
As far as I know, glibc can not be statically linked - so apps, that are packaged with this tool would not work on the systems with older version of glibc than the machine, on which it was compiled on.
For example, a programme compiled on ubuntu 20.04 won't work on ubuntu 18.04 because of that, even if you use static version of qt libraries.
The only solution for this problem is to compile apps on oldest, still supported platforms (which is, I guess, ubuntu 16.04). Linuxdeployqt forces you to do so. As far as I know there is no workaround.

Here is what I do: I use modern platform to develop my app, but final compilation is made on mint 18 (based on ubuntu 16.04). On this older platform I use linuxdeployqt to pack my app.

Hope this helps.

**Comment by probonopd** [comment]
Ubuntu 20.04.2 LTS is too new.
Please run on a Ubuntu Xenial.
This is so that the resulting bundle will work on most still-supported Linux distributions.

**Comment by pedro1713** [comment]
I thought this was a tool. Why wouldn't it allow the user to run on a newer system. It is OK to suggest a proper way to use the tool, but to force the user is wrong. It should at least provide an override option.

**Comment by probonopd** [comment]
>  Why wouldn't it allow the user to run on a newer system. 

Beacause it would then produce AppImages that would not run on all still-supported operating systems and would, hence, be broken by definition.
