### ISSUE TITLE
Questions about using the oldest supported Ubuntu

### ISSUE THREAD

**Issue by jerkstorecaller** [probonopd/linuxdeployqt#516]
I agree with this project's goal of producing widely-compatible AppImages. (though it forces this decision even on people who aren't making AppImages, and who just want a simple way to copy a Qt binary's dependencies to an output directory)

As a Linux desktop user, I'm wondering:

1. Do you have any real-world insights about whether the AppImages you produce on Ubuntu 16.04 (or was it 18.04?) are running fine on different families like Fedora, RH, Arch? Issue tracker doesn't seem to have any complaints, that's good!
2. Why make the bottom limit Ubuntu 16.04? If the goal is wide compatibility, why not suggest the distro with the oldest glibc supported by Qt, even if it's just in a stdout message? Was 16.04 picked as a balance between compatibility and security fixes (in glibc, libstdc++, etc)?

**Comment by Light-Wizzard** [comment]
The oldest LTS is Ubuntu 18.04.6 with an End of Standard Support on April 2023, 16 went out in April 2021, and regardless of all the issues, its still the philosophy of this project to be compatible with the last, which means 2 or 3 LTS in lag time, this is because most of the compiler services like Travis or AppVeyor will support it, as well as a lot of the general public who do not update for some reason, if you have an issue with that, you should look at [Linux Deploy](https://github.com/linuxdeploy/linuxdeploy).

Hope that helped answer your question, Flesh

**Comment by probonopd** [comment]
> Do you have any real-world insights about whether the AppImages you produce on Ubuntu 16.04 (or was it 18.04?) are running fine on different families like Fedora, RH, Arch? Issue tracker doesn't seem to have any complaints, that's good!

AppImages made on older releases of the operating system should always be able to run on newer versions of the operating system, or else it's a bug in the operating system.

> Why make the bottom limit Ubuntu 16.04?

Our general recommendation is to use a distribution no newer than the oldest still-supported LTS release of Ubuntu, whcih currently happens to be Ubuntu 18.04.x LTS (Bionic Beaver). That is also what we test the AppImages against.
