### ISSUE TITLE
It doesn't work on arch-based distros

### ISSUE THREAD

**Issue by mede-erik** [probonopd/linuxdeployqt#543]
The program always gets the same error both installed by the AUR and compiled:
Aur:
`linuxdeployqt 8 (commit d41e234), build <local dev build> built on 2022-08-03 16:15:17 UTC
ERROR: The host system is too new.
Please run on a system with a glibc version no newer than what comes with the oldest
currently still-supported mainstream distribution (xenial), which is glibc 2.23.
This is so that the resulting bundle will work on most still-supported Linux distributions.
For more information, please see
https://github.com/probonopd/linuxdeployqt/issues/340
`
The glibc package is installed.

**Comment by probonopd** [comment]
Looks like it works as intended.
What makes you think otherwise?

**Comment by mede-erik** [comment]
because when I run `linuxdeployqt terminal/terminal` this command just prints me the text above without working

**Comment by probonopd** [comment]
The text explains that your host system is too new, and that you need to run it on an older system. It works as intended, because it prevents you from making AppDirs or AppImages on this "too new " system, because the resuting AppDirs or AppImages would not be able to run on all still-supported versions of mainstream distributions.

Please run linuxdeployqt on, e.g, Ubuntu 18.04 LTS (Bionic Beaver). And please use the version from https://github.com/probonopd/linuxdeployqt/releases/tag/continuous and not the outdated version `linuxdeployqt 8 (commit d41e234)`.

**Comment by mede-erik** [comment]
thank you very much for the advice, i will try to use it on ubuntu 18.04
