### ISSUE TITLE
Qt binary packages are linked with unsupported glibc 2.28

### ISSUE THREAD

**Issue by syyyr** [probonopd/linuxdeployqt#566]
Hi, the binary packages available for Qt [are linked against glibc 2.28](https://doc.qt.io/qt-6/supported-platforms.html#availability-of-packages), however, linuxdeployqt only supports glibc 2.27, so I'm not able to use them. What should I do in this case? Build Qt from sources?

Thanks.

**Comment by probonopd** [comment]
Use an older version of Qt that is linked against an older glibc, or wait until April. Then the oldest still-supported Ubuntu LTS will be a newer one, hence a newer glibc will be acceptable.

(Or bundle glibc along with your application, e.g., using go-appimage `appimagetool -s deploy` instead of linuxdeployqt.)
