### ISSUE TITLE
Decide which libraries to bundle and which libraries not to bundle

### ISSUE THREAD

**Issue by probonopd** [probonopd/linuxdeployqt#6]
We need to decide which libraries to bundle and which libraries not to bundle. Normally we will want to bundle things like libQt\* but not bundle glibc*.

Currently this is done in a (too) simplistic way that also breaks on build systems that have no more `/lib`, e.g., Fedora:

```
    if (trimmed.startsWith("/lib"))
        return info;
```

Something more elaborated along the lines of a [blacklist](https://github.com/probonopd/AppImages/blob/master/excludelist) will be needed.

**Comment by ddurham2** [comment]
Not sure i get the problem.  You want to run something like ldd to tell you which libraries a specified application requires.  Then filter for any names like libQt5*.  Don't bundle any other system libraries.  The output should be parsed only for names and not for the actual paths found.  And LD_LIBRARY_PATH should probably be prefixed with the install directory of Qt when ldd is run so that it can find the Qt libs regardless of what may or may not be on the system.  (NOTE: another tool like readelf might be more appropriate, but ldd is going to recur on the dependencies (IIRC) which saves you some trouble, and I've never found ldd not to be on a system).

The existing windeployqt maps module names to required plugin families which should also be pulled in.   In my bash script version of libdeployqt, I also ran ldd on any plugin libs from the plugin familiar directory to determine if any other modules were required (e.g. libQt5Svn) and then repeated the process on any newly found module libs.

Only, the windeployqt's list of modules needs to include additional libs like libQt5X11Extras and others (also in my bash script).   A mapping like this, should be common across all variants of deployqt tools (per thiago's suggestion too).

**Comment by probonopd** [comment]
>  Then filter for any names like libQt5*. Don't bundle any other system libraries.

At the moment I am bundling too much, but I don't think that filtering for names like libQt5* is the correct solution, but restricting to stuff coming from the path to the install directory of Qt probably is.

I think we should also bundle Qt only if the path to the install directory of Qt does not start with `/usr/lib` or `lib` in order to prevent from distribution-provided Qt to be bundled, since this might pull in other dependencies from the distribution which would hinder portability across distributions. The Qt-provided Qt binaries are speficially compiled to be compatible with a wide variety of distributions (built on CentOS 6). There could be a command line switch to override this.

What about other 3rd-party libraries the application might depend on, let's say `libmygreatappfunctions.so.0`?

> The output should be parsed only for names and not for the actual paths found.

Why? How is linuxdeployqt then supposed to find out where to copy the libraries from?

> LD_LIBRARY_PATH should probably be prefixed with the install directory of Qt when ldd is run so that it can find the Qt libs regardless of what may or may not be on the system

Yes, but prefixed with what? Where do I know the path to the install directory of Qt from?

> Only, the windeployqt's list of modules needs to include additional libs like libQt5X11Extras and others (also in my bash script).

Can you explain this point a bit more, I don't understand this.

> A mapping like this, should be common across all variants of deployqt tools (per thiago's suggestion too).

Where did he suggest what?

**Comment by probonopd** [comment]
macdeployqt deploys the Qt plugins according to the following [rules](http://doc.qt.io/qt-4.8/deployment-mac.html):

- Debug versions of the plugins are not deployed.
-     The designer plugins are not deployed.
-     The Image format plugins are always deployed.
-     SQL driver plugins are deployed if the application uses the QtSql module.
-     Script plugins are deployed if the application uses the QtScript module.
-     The Phonon backend plugin is deployed if the application uses the Phonon module.
-     The svg icon plugin is deployed if the application uses the QtSvg module.
-     The accessibility plugin is always deployed.
-     Accessibility for Qt3Support is deployed if the application uses the Qt3Support module.

Note: If you want a 3rd party library to be included in your application bundle, then you must copy the library into the bundle manually, after the bundle is created.

**Comment by probonopd** [comment]
Please comment if you feel this should be reopened.
