### ISSUE TITLE
Can you share .iso file or VM with linux distro with installed linuxdeployqt and latest Qt, that can be used for deployement.

### ISSUE THREAD

**Issue by 88aleksandr88** [probonopd/linuxdeployqt#602]
Hello.
Can you share .iso file or VM with linux distro with installed linuxdeployqt and latest Qt, that can be used for deployement.
Compile Qt 6.6.4 for Cent OS 7 is difficult task. Can you provide an up-to-date distro for deployement?

**Comment by TheAssassin** [comment]
CentOS 7 will (finally!) no longer be "supported" by the end of June. That's around 3 months from now. Of a 10 year total "support" time. Given the fact that Red Hat gave up on CentOS years ago and that the successor (!) has gone EOL already, I'd suggest you stop worrying about CentOS 7 and use a more modern distribution right away.

Qt 6 does not support CentOS officially anyway.

**Comment by 88aleksandr88** [comment]
Can you share your distro with users as iso or vm with latest qt for deployement, for no one will need create this distro for himself?

**Comment by TheAssassin** [comment]
No. I doubt that exists. A workflow that involved a separate ISO/VM just for building is just not modern any longer, hasn't been ever since Docker has existed, so no, there is no such thing. Also, Qt can be installed using the upstream installer, for instance, there is not even a need for a special distribution.

I suggest you use Ubuntu 20.04 and the Qt binary installer.

**Comment by probonopd** [comment]
...or Qt from https://launchpad.net/~beineri, which is what I am using :)

**Comment by TheAssassin** [comment]
That PPA hasn't provided the most recent Qt in years, though.

**Comment by probonopd** [comment]
True. And I am no longer actively working on this codebase in favor of https://github.com/probonopd/go-appimage.
