### ISSUE TITLE
runPatchelf: "patchelf: cannot find section '.dynamic'\n"

### ISSUE THREAD

**Issue by AIIX** [probonopd/linuxdeployqt#61]
./linuxdeployqt-continuous-x86_64.AppImage /home/Aix/build-mycroft-qtapplication-Desktop-Release/mycroft-qtapplication -no-strip -appimage -bundle-non-qt-libs -qmldir=/home/Aix/build-mycroft-qtapplication-Desktop-Release/qml/ -verbose=3

Log: Using patchelf:
Log:  change rpath in "/home/Aix/release-mycroft-qtapplication/lib//libnsl.so.1"
Log:  to "$ORIGIN"
ERROR: runPatchelf: "patchelf: cannot find section '.dynamic'\n"
ERROR: runPatchelf: ""

Distro: Fedora 25 Plasma 5 Using Distribution QT5 and QtCreator

**Comment by probonopd** [comment]
Thanks for reporting @AIIX.

Sounds to a patchelf issue similar to https://github.com/NixOS/patchelf/issues/66. Please report this to https://github.com/NixOS/patchelf/issues, ideally with the library attached as an example.

**Comment by probonopd** [comment]
Fixed and (hopefully) working, please try https://github.com/probonopd/linuxdeployqt/releases/tag/continuous. Turns out that `strip` has a bug that cripples binaries on which `patchelf` was previously run (https://github.com/NixOS/patchelf/issues/10). Therefore, I am now checking whether a binary has a `rpath` starting with $ (indicating that we already ran `patchelf` on it), and _not_ run `strip` in that case. https://github.com/probonopd/linuxdeployqt/commit/c643d6a5094f1dafcf0dc82c33d11d24ec622876

Let me know if this solves it for you.

**Comment by probonopd** [comment]
With https://github.com/NixOS/patchelf/pull/117 merged, patchelf will hopefully allow binaries to be stripped after running patchelf.
