### ISSUE TITLE
Why do the releases say "Do not use anymore"?

### ISSUE THREAD

**Issue by benma** [probonopd/linuxdeployqt#624]
E.g. https://github.com/probonopd/linuxdeployqt/releases/tag/9

I get that according to the README, linuxdeployqt is not maintained anymore:

> Please note: As of 2024 , I am no longer actively working on this codebase in favor of https://github.com/probonopd/go-appimage.

But why mark the previous releases as "Do not use anymore"? Is there a specific reason that they should not be used?

The proposed alternative at https://github.com/probonopd/go-appimage/blob/master/src/appimagetool/README.md seems like it's not a viable alternative right now, at least when using QtWebEngine:

> This is an **experimental** implementation 
> [...]
> Bundle QtWebEngine (untested)

So using the existing releases of this repo cannot be avoided without a lot of effort.

**Comment by probonopd** [comment]
The old versions are there for historical reasons. They may contain issues that will not be addressed there, but may already have been addressed in the continuous build. The note is there so that no one assumes that the old versions are still supported. If you understand this and still want to use an old version, you are of course free to do so.
