### ISSUE TITLE
Appimage not created 

### ISSUE THREAD

**Issue by keshavbhatt** [probonopd/linuxdeployqt#63]
hi am trying to creae appimage of mt qt application ,
first i used linuxqtdeploy to create appimgae dir with libs and stuffs my binary need then i used appimagetool as below , which gave me following errors 

./appimagetool-x86_64.AppImage ../ktube-media-downloader.AppDir/
Arch: 86_64
DESTINATION not specified, so assuming Ktube_Media_Downloader-x86_64.AppImage
/home/bulld/linuxdeployqt/ktube-media-downloader.AppDir should be packaged as Ktube_Media_Downloader-x86_64.AppImage
AppStream upstream metadata found in usr/share/metainfo/ktube-media-downloader.appdata.xml

(appstreamcli:1165): GLib-ERROR **: /build/glib2.0-7IO_Yw/glib2.0-2.48.1/./glib/gmem.c:100: failed to allocate 18446744073700673569 bytes
Trace/breakpoint trap (core dumped)
Failed to validate AppStream information with appstreamcli

**Comment by probonopd** [comment]
Please try to run [appimagetool](https://github.com/probonopd/AppImageKit/releases) manually on your AppDir, using the `-n` switch. I suspect this to be an issue with appstreamcli, cc'ing @ximion.

**Comment by probonopd** [comment]
Note to self: If this turns out to be the case, consider making `-n` the default for linuxdeployqt.

**Comment by ximion** [comment]
`failed to allocate 18446744073700673569 bytes` - urgh... Something odd is happening there.
Please run `appstreamcli --version` and tell me which version of AppStream you are using.

**Comment by supertriodo** [comment]
First, great work you are doing with this tool, its amazing!

I've been trying to make the appimage file using the -appimage argument but it didn't actually create the file. I had to run the command appimagetool and everything worked. Is this way how it is suposed to work?


`triodo@led ~/Documentos/build-ArenaTracker-Desktop-Release $ appimagetool .
WARNING: appstreamcli is missing, please install it if you want to use AppStream metadata
WARNING: appstream-util is missing, please install it if you want to use AppStream metadata
Arch: 86_64
DESTINATION not specified, so assuming Arena_Tracker-x86_64.AppImage
/home/triodo/Documentos/build-ArenaTracker-Desktop-Release should be packaged as Arena_Tracker-x86_64.AppImage
/home/triodo/Documentos/build-ArenaTracker-Desktop-Release/icon{.png,.svg,.svgz,.xpm} not present but defined in desktop file
triodo@led ~/Documentos/build-ArenaTracker-Desktop-Release $ appimagetool .
WARNING: appstreamcli is missing, please install it if you want to use AppStream metadata
WARNING: appstream-util is missing, please install it if you want to use AppStream metadata
Arch: 86_64
DESTINATION not specified, so assuming Arena_Tracker-x86_64.AppImage
/home/triodo/Documentos/build-ArenaTracker-Desktop-Release should be packaged as Arena_Tracker-x86_64.AppImage
WARNING: AppStream upstream metadata is missing, please consider creating it
         in usr/share/metainfo/default.appdata.xml
         Please see https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html#sect-Quickstart-DesktopApps
         for more information.
Generating squashfs...
Parallel mksquashfs: Using 8 processors
Creating 4.0 filesystem on Arena_Tracker-x86_64.AppImage, block size 131072.
[=================================================================================================================================|] 717/717 100%

Exportable Squashfs 4.0 filesystem, gzip compressed, data block size 131072
	compressed data, compressed metadata, compressed fragments, no xattrs
	duplicates are removed
Filesystem size 30840.90 Kbytes (30.12 Mbytes)
	39.44% of uncompressed filesystem size (78193.44 Kbytes)
Inode table size 3474 bytes (3.39 Kbytes)
	48.97% of uncompressed inode table size (7094 bytes)
Directory table size 1582 bytes (1.54 Kbytes)
	43.86% of uncompressed directory table size (3607 bytes)
Number of duplicate files found 1
Number of inodes 146
Number of files 140
Number of fragments 28
Number of symbolic links  2
Number of device nodes 0
Number of fifo nodes 0
Number of socket nodes 0
Number of directories 4
Number of ids (unique uids + gids) 1
Number of uids 1
	root (0)
Number of gids 1
	root (0)
Embedding ELF...
Marking the AppImage as executable...
Success
`

**Comment by probonopd** [comment]
Hi @supertriodo 

The error you were getting, `/home/triodo/Documentos/build-ArenaTracker-Desktop-Release/icon{.png,.svg,.svgz,.xpm} not present but defined in desktop file`, indicates that you have not set an icon in your desktop file. Please put in a desktop file and an icon, both in the top level directory.
A default.desktop file has been generated for you, but you should rename and edit it, and have it point to a valid icon.

**Comment by supertriodo** [comment]
I put two different commands from the terminal by error, now is fixed in my previous post. I think appimagetool found the image but it doesn't show it.

**Comment by ximion** [comment]
@probonopd Btw, just because I noticed this: You don't strictly need `appstream-util` as well as `appstreamcli` - if `appstreamcli` validates the file, everything is fine (spec-compliance is guaranteed) - having additional validation doesn't hurt though, but appstream-util might access the internet if that is not explicitly disallowed.

Appstreamcli allows you to generate a metainfo file from a .desktop file: `appstreamcli new-template desktop-application --from-desktop /path/to/desktopfile.desktop` - however, this will add template dummy entries for every tag that should be there, for the developer to fill out (e.g. for the description tag).
If needed, I could make a version of this call which only does format conversion (but I am not quite sure what you do with this generally, since the resulting metainfo file will never have more information than its source .desktop file, one could read from the .desktop file directly)

**Comment by probonopd** [comment]
@ximion back when I added the two tools i noticed that i got different results from them. So your recommendation would be to just use `appstreamcli`?
I know about generating the metainfo file, but the autogenerated metainfo file immediately fails validation, thus probably driving users crazy. This is why I haven't used it so far.

**Comment by ximion** [comment]
@probonopd Nah, using both is fine, but I probably wouldn't fail if `appstream-util` is missing. `appstreamcli` validates the structure of the XML and a few other parts by-the-latter, so if that passes, the file is generally fine. `appstream-util` does that and also includes a few additional checks which are useful for GNOME Software, e.g. that tool also complains if certain optional tags are missing that would improve the metadata, or does some validation on the screenshots and description paragraphs.

And yeah, the autogenerated file fails validation because it's just a template :P

**Comment by probonopd** [comment]
For now, linuxdeployqt disables the AppStream checking built into appimagetool. To be reconsidered at a later point.
